zeppelin:
    image: dylanmei/zeppelin
    container_name: zeppelin
    environment:
        ZEPPELIN_PORT: 8090
        ZEPPELIN_JAVA_OPTS: >-
            -Dspark.driver.memory=1g
            -Dspark.executor.memory=2g
        MASTER: local[*]
    ports:
        - 8090:8090
    volumes:
        - ./data:/usr/zeppelin/data
        - ./notebook:/usr/zeppelin/notebook